# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_upper_diagonal_index <- function(i, j) {
    .Call('MicrocreditLRVB_get_upper_diagonal_index', PACKAGE = 'MicrocreditLRVB', i, j)
}

r_mulitvariate_digamma <- function(x, p) {
    .Call('MicrocreditLRVB_r_mulitvariate_digamma', PACKAGE = 'MicrocreditLRVB', x, p)
}

GetWishartEntropy <- function(v_par_r, n_par_r) {
    .Call('MicrocreditLRVB_GetWishartEntropy', PACKAGE = 'MicrocreditLRVB', v_par_r, n_par_r)
}

r_GetELogDetWishart <- function(v_par_r, n_par_r) {
    .Call('MicrocreditLRVB_r_GetELogDetWishart', PACKAGE = 'MicrocreditLRVB', v_par_r, n_par_r)
}

ModelGradient <- function(r_x, r_y, r_y_g, r_vp, r_pp, calculate_hessian, unconstrained) {
    .Call('MicrocreditLRVB_ModelGradient', PACKAGE = 'MicrocreditLRVB', r_x, r_y, r_y_g, r_vp, r_pp, calculate_hessian, unconstrained)
}

EncodeLambda <- function(r_vp, k, n_g, lambda_diag_min, n_min) {
    .Call('MicrocreditLRVB_EncodeLambda', PACKAGE = 'MicrocreditLRVB', r_vp, k, n_g, lambda_diag_min, n_min)
}

DecodeLambda <- function(theta, k, n_g, lambda_diag_min, n_min) {
    .Call('MicrocreditLRVB_DecodeLambda', PACKAGE = 'MicrocreditLRVB', theta, k, n_g, lambda_diag_min, n_min)
}

DecodeParameters <- function(theta, r_vp, r_pp, unconstrained_wishart) {
    .Call('MicrocreditLRVB_DecodeParameters', PACKAGE = 'MicrocreditLRVB', theta, r_vp, r_pp, unconstrained_wishart)
}

LambdaGradient <- function(x, y, y_g, r_vp, r_pp, unconstrained) {
    .Call('MicrocreditLRVB_LambdaGradient', PACKAGE = 'MicrocreditLRVB', x, y, y_g, r_vp, r_pp, unconstrained)
}

LambdaEntropyDerivs <- function(x, y, y_g, r_vp, r_pp, unconstrained) {
    .Call('MicrocreditLRVB_LambdaEntropyDerivs', PACKAGE = 'MicrocreditLRVB', x, y, y_g, r_vp, r_pp, unconstrained)
}

LambdaLikelihoodMomentDerivs <- function(x, y, y_g, r_vp, r_pp, unconstrained) {
    .Call('MicrocreditLRVB_LambdaLikelihoodMomentDerivs', PACKAGE = 'MicrocreditLRVB', x, y, y_g, r_vp, r_pp, unconstrained)
}

WishartMomentParameterizationJacobian <- function(r_vp, r_pp, unconstrained) {
    .Call('MicrocreditLRVB_WishartMomentParameterizationJacobian', PACKAGE = 'MicrocreditLRVB', r_vp, r_pp, unconstrained)
}

TestJacobian <- function() {
    .Call('MicrocreditLRVB_TestJacobian', PACKAGE = 'MicrocreditLRVB')
}

PriorSensitivity <- function(r_vp, r_pp) {
    .Call('MicrocreditLRVB_PriorSensitivity', PACKAGE = 'MicrocreditLRVB', r_vp, r_pp)
}

GetParameterEncoder <- function(r_vp, r_pp) {
    .Call('MicrocreditLRVB_GetParameterEncoder', PACKAGE = 'MicrocreditLRVB', r_vp, r_pp)
}

GetPriorParameterEncoder <- function(r_pp) {
    .Call('MicrocreditLRVB_GetPriorParameterEncoder', PACKAGE = 'MicrocreditLRVB', r_pp)
}

GetModelParameterEncoder <- function(r_vp, r_pp) {
    .Call('MicrocreditLRVB_GetModelParameterEncoder', PACKAGE = 'MicrocreditLRVB', r_vp, r_pp)
}

GetVariationalCovariance <- function(vp_params, r_pp) {
    .Call('MicrocreditLRVB_GetVariationalCovariance', PACKAGE = 'MicrocreditLRVB', vp_params, r_pp)
}

