# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

GetEmptyVariationalParameters <- function(k, n_g) {
    .Call('MicrocreditLRVB_GetEmptyVariationalParameters', PACKAGE = 'MicrocreditLRVB', k, n_g)
}

GetEmptyPriors <- function(k) {
    .Call('MicrocreditLRVB_GetEmptyPriors', PACKAGE = 'MicrocreditLRVB', k)
}

GetParametersFromVector <- function(r_vp, r_theta, unconstrained) {
    .Call('MicrocreditLRVB_GetParametersFromVector', PACKAGE = 'MicrocreditLRVB', r_vp, r_theta, unconstrained)
}

GetVectorFromParameters <- function(r_vp, unconstrained) {
    .Call('MicrocreditLRVB_GetVectorFromParameters', PACKAGE = 'MicrocreditLRVB', r_vp, unconstrained)
}

GetParametersFromGlobalVector <- function(r_vp, r_theta, unconstrained) {
    .Call('MicrocreditLRVB_GetParametersFromGlobalVector', PACKAGE = 'MicrocreditLRVB', r_vp, r_theta, unconstrained)
}

GetGlobalVectorFromParameters <- function(r_vp, unconstrained) {
    .Call('MicrocreditLRVB_GetGlobalVectorFromParameters', PACKAGE = 'MicrocreditLRVB', r_vp, unconstrained)
}

GetMomentsFromVector <- function(r_mp, r_theta) {
    .Call('MicrocreditLRVB_GetMomentsFromVector', PACKAGE = 'MicrocreditLRVB', r_mp, r_theta)
}

GetVectorFromMoments <- function(r_mp) {
    .Call('MicrocreditLRVB_GetVectorFromMoments', PACKAGE = 'MicrocreditLRVB', r_mp)
}

GetPriorsFromVector <- function(r_pp, r_theta) {
    .Call('MicrocreditLRVB_GetPriorsFromVector', PACKAGE = 'MicrocreditLRVB', r_pp, r_theta)
}

GetVectorFromPriors <- function(r_pp) {
    .Call('MicrocreditLRVB_GetVectorFromPriors', PACKAGE = 'MicrocreditLRVB', r_pp)
}

GetPriorsAndParametersFromVector <- function(r_vp, r_pp, r_theta) {
    .Call('MicrocreditLRVB_GetPriorsAndParametersFromVector', PACKAGE = 'MicrocreditLRVB', r_vp, r_pp, r_theta)
}

GetElboDerivatives <- function(r_x, r_y, r_y_g, r_vp, r_pp, calculate_gradient, calculate_hessian, unconstrained) {
    .Call('MicrocreditLRVB_GetElboDerivatives', PACKAGE = 'MicrocreditLRVB', r_x, r_y, r_y_g, r_vp, r_pp, calculate_gradient, calculate_hessian, unconstrained)
}

GetCustomElboDerivatives <- function(r_x, r_y, r_y_g, r_vp, r_pp, include_obs, include_hier, include_prior, include_entropy, global_only, calculate_gradient, calculate_hessian, unconstrained) {
    .Call('MicrocreditLRVB_GetCustomElboDerivatives', PACKAGE = 'MicrocreditLRVB', r_x, r_y, r_y_g, r_vp, r_pp, include_obs, include_hier, include_prior, include_entropy, global_only, calculate_gradient, calculate_hessian, unconstrained)
}

GetMoments <- function(r_vp) {
    .Call('MicrocreditLRVB_GetMoments', PACKAGE = 'MicrocreditLRVB', r_vp)
}

GetMomentJacobian <- function(r_vp, unconstrained) {
    .Call('MicrocreditLRVB_GetMomentJacobian', PACKAGE = 'MicrocreditLRVB', r_vp, unconstrained)
}

GetSparseELBOHessian <- function(r_x, r_y, r_y_g, r_vp, r_pp, unconstrained) {
    .Call('MicrocreditLRVB_GetSparseELBOHessian', PACKAGE = 'MicrocreditLRVB', r_x, r_y, r_y_g, r_vp, r_pp, unconstrained)
}

GetLogPriorDerivatives <- function(r_vp, r_pp, calculate_gradient, calculate_hessian, unconstrained) {
    .Call('MicrocreditLRVB_GetLogPriorDerivatives', PACKAGE = 'MicrocreditLRVB', r_vp, r_pp, calculate_gradient, calculate_hessian, unconstrained)
}

GetLogVariationalDensityDerivatives <- function(r_obs_mp, r_vp, r_pp, include_mu, include_lambda, r_include_mu_groups, r_include_tau_groups, calculate_gradient) {
    .Call('MicrocreditLRVB_GetLogVariationalDensityDerivatives', PACKAGE = 'MicrocreditLRVB', r_obs_mp, r_vp, r_pp, include_mu, include_lambda, r_include_mu_groups, r_include_tau_groups, calculate_gradient)
}

GetMCMCLogPriorDerivatives <- function(draw_list, r_pp) {
    .Call('MicrocreditLRVB_GetMCMCLogPriorDerivatives', PACKAGE = 'MicrocreditLRVB', draw_list, r_pp)
}

GetCovariance <- function(r_vp) {
    .Call('MicrocreditLRVB_GetCovariance', PACKAGE = 'MicrocreditLRVB', r_vp)
}

EvaluateLKJPriorVB <- function(r_v, n, alpha, beta, eta) {
    .Call('MicrocreditLRVB_EvaluateLKJPriorVB', PACKAGE = 'MicrocreditLRVB', r_v, n, alpha, beta, eta)
}

EvaluateLKJPriorDraw <- function(r_sigma, log_det_sigma, alpha, beta, eta) {
    .Call('MicrocreditLRVB_EvaluateLKJPriorDraw', PACKAGE = 'MicrocreditLRVB', r_sigma, log_det_sigma, alpha, beta, eta)
}

